# Base image
FROM node:18.15.0 AS base

# Set working directory
WORKDIR /app

# Install dependencies
RUN apt-get update && \
    apt-get -y install --no-install-recommends \
        vim \
        git \
        sudo \
        openssh-client \
        xdg-utils \ 
        && \
    npm install -g @ionic/cli && \
    npm cache clean --force && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Expose ports for Ionic
EXPOSE 8100/tcp
EXPOSE 8101/tcp
EXPOSE 35729/tcp

# Defining an entrypoint forces the container to continue running
#ENTRYPOINT ["tail", "-f", "/dev/null"]

# Start the Ionic dev server
CMD ["ionic", "serve", "--lab"]
